<?
    /** @var array $ActiveUser текущий залогиненый заказчик */

    load('Avaritia\Model\Customer\Customer');
    load('Avaritia\Library\Session');

    use Avaritia\Model\Customer\Customer;
    use Avaritia\Library\Session;
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Avaritia</title>
    <link rel="stylesheet" href="css/vendor/bootstrap-3.3.5.min.css">
    <link rel="stylesheet" href="css/avaritia/avaritia_<?=REVISION; ?>.css">
</head>
<body>
<div class="container">
    <div class="page-header">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <h1 class="text-center">
                    <small><span class="glyphicon glyphicon-piggy-bank"></span></small>
                    Avaritia: заказчик
                </h1>
            </div>
            <div class="col-md-3">
                <div class="panel panel-default">
                    <div class="panel-body text-center">
                        <?=Customer\getFio($ActiveUser); ?>
                        <form method="POST" action="/index/logout">
                            <div class="form-group">
                                <button type="submit" name="logout" class="btn btn-danger">Выход</button>
                                <input type="hidden" name="token" value="<?=Session\getToken(); ?>" />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">

    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h2>Новый заказ</h2>
            <div class="alert alert-success" id="successMessage"></div>
            <div class="alert alert-danger" id="failMessage"></div>
            <div class="form-group">
                <textarea class="form-control" rows="10" id="text" placeholder="Текст (не более 1024 символа)"></textarea>
            </div>
            <div class="form-group">
                <input type="text" class="form-control" id="price" placeholder="Цена (целое число в рублях)" pattern="a*">
            </div>
            <div class="form-group">
                <input type="button" class="btn btn-success" id="saveOrder" value="Сохранить">
            </div>
            <input type="hidden" id="token" value="<?=Session\getToken(); ?>" />
        </div>
    </div>
    <div class="loader modal fade"><i></i></div>
</div>
<!-- scripts -->
<script src="js/vendor/jquery-2.1.4.min.js"></script>
<script src="js/vendor/bootstrap-3.3.5.min.js"></script>
<script src="js/avaritia/config_<?=REVISION; ?>.js"></script>
<script src="js/avaritia/api_<?=REVISION; ?>.js"></script>
<script src="js/avaritia/customer_<?=REVISION; ?>.js"></script>
</body>
</html>