<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Avaritia</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <div class="page-header">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <h1 class="text-center">
                    <small><span class="glyphicon glyphicon-piggy-bank"></span></small>
                    Avaritia
                </h1>
            </div>
            <div class="col-md-3">
                <div class="panel panel-default">
                    <div class="panel-body text-center">
                        email@email.com
                        <a href=""><i class="glyphicon glyphicon-off"></i></a>
                        <div>
                            <i class="glyphicon glyphicon-ruble"></i>
                            <b>100.50</b>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- scripts -->
<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</body>
</html>