<?
    /** @var array $ActiveUser текущий залогиненый исполнитель */
    /** @var array $Orders список заказов */

    load('Avaritia\Model\Executor\Executor');
    load('Avaritia\Library\Session');
    load('Avaritia\Model\Order\Order');

    use Avaritia\Model\Executor\Executor;
    use Avaritia\Library\Session;
    use Avaritia\Model\Order\Order;
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Avaritia</title>
    <link rel="stylesheet" href="css/vendor/bootstrap-3.3.5.min.css">
    <link rel="stylesheet" href="css/avaritia/avaritia_<?=REVISION; ?>.css">
</head>
<body>
<div class="container">
    <div class="page-header">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <h1 class="text-center">
                    <small><span class="glyphicon glyphicon-piggy-bank"></span></small>
                    Avaritia: исполнитель
                </h1>
            </div>
            <div class="col-md-3">
                <div class="panel panel-default">
                    <div class="panel-body text-center">
                        <?=Executor\getFio($ActiveUser); ?>
                        <div>
                            <i class="glyphicon glyphicon-ruble"></i>
                            <b id="salary"><?=Executor\getSalary($ActiveUser); ?></b>
                        </div>
                        <form method="POST" action="/index/logout">
                            <div class="form-group">
                                <button type="submit" name="logout" class="btn btn-danger">Выход</button>
                                <input type="hidden" name="token" value="<?=Session\getToken(); ?>" />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="row">

    </div>
    <div class="row">
        <div class="col-md-12">
            <h2>Список заказов</h2>
            <div class="alert alert-success" id="successMessage"></div>
            <div class="alert alert-danger" id="failMessage"></div>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Id</th>
                    <th class="text-center">Стоимость, руб</th>
                    <th>Текст заказа</th>
                    <th></th>
                </tr>
                </thead>
                <tbody id="orders-list">
                <!-- список заказов подгружается ajax-ом -->
                </tbody>
            </table>
        </div>
    </div>
    <input type="hidden" id="token" value="<?=Session\getToken(); ?>" />
    <div class="loader modal fade"><i></i></div>
</div>
<!-- scripts -->
<script src="js/vendor/jquery-2.1.4.min.js"></script>
<script src="js/vendor/bootstrap-3.3.5.min.js"></script>
<script src="js/avaritia/config_<?=REVISION; ?>.js"></script>
<script src="js/avaritia/api_<?=REVISION; ?>.js"></script>
<script src="js/avaritia/executor_<?=REVISION; ?>.js"></script>
</body>
</html>